hmcts/fact-frontend

jest.smoke.config.js, package.json, src/test/smoke/smoke.ts
https://tools.hmcts.net/jira/browse/CTF-31
Add smoke test.
```
[ ] Yes
[x] No
```
=> Add smoke test

config/default.json, src/main/app.ts, src/main/assets/scss/main.scss, src/main/views/home.njk, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/CTF-11
Add home page
```
[ ] Yes
[x] No
```
=> CTF-11: Add home page

.gitignore, src/main/locales/cy/search/location.json, src/main/locales/cy/search/option.json, src/main/views/search/location.njk, src/main/views/search/option.njk
=> Ctf 38 clean up

src/main/container.ts, src/main/controllers/ChooseActionController.ts, src/main/controllers/search/SearchOptionController.ts, src/main/interfaces/FactRequest.ts, src/main/locales/en/choose-action.json, src/main/routes.ts, src/main/views/choose-action.njk, src/main/views/template.njk, src/test/functional/features/no-name.feature, src/test/functional/steps/no-name.ts, src/test/unit/test/controllers/ChooseActionController.ts, src/test/unit/test/controllers/search/SearchOptionController.ts
https://tools.hmcts.net/jira/browse/CTF-57
User story 57 - court name not known and functional tests and unit tests.
Update to template to include service name header.
```
[ ] Yes
[ X ] No
```
=> Ctf 57 select court option

src/main/interfaces/FactRequest.ts, src/main/modules/i18next/index.ts, src/test/unit/test/utils/FactApi.ts, src/test/unit/test/utils/healthOptions.ts
Sonar: https://sonarcloud.io/component_measures?id=fact-frontend&metric=lines_to_cover&selected=fact-frontend%3Asrc%2Fmain%2Futils%2FhealthOptions.ts&view=list
Updated test coverage for healthOptions.
```
[ ] Yes
[ X ] No
```
=> coverage: update healthOptions unit test

src/main/views/choose-action.njk, src/main/views/search/option.njk, src/test/a11y/a11y.ts
https://tools.hmcts.net/jira/browse/FACT-72
Add initial Pa11y tests and fix accessibility errors
```
[ ] Yes
[x] No
```
=> Fact 72 add pa11y tests

src/main/controllers/CourtDetailsController.ts, src/main/controllers/search/LocationSearchController.ts, src/main/controllers/search/SearchOptionController.ts, src/main/controllers/search/SearchResultsController.ts, src/main/routes.ts, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/main/views/search/location.njk, src/test/a11y/a11y.ts, src/test/unit/test/controllers/CourtDetailsController.ts, src/test/unit/test/controllers/search/LocationSearchController.ts, src/test/unit/test/controllers/search/SearchOptionController.ts, src/test/unit/test/controllers/search/SearchResultsController.ts
=> fact-45-fix

README.md, package.json, src/test/a11y/a11y.ts
https://tools.hmcts.net/jira/browse/FACT-45
Update Pa!!y tests for search details page
```
[ ] Yes
[ x] No
```
=> Update pally tests for search details page

api/court-details.json, src/main/locales/en/court-details.json, src/main/views/court-details/in-person-court.njk, src/test/functional/features/court-details.feature, src/test/functional/steps/court-details.ts
=> Fact 102 access scheme

src/main/controllers/service/ChooseServiceAreaController.ts, src/main/controllers/service/ChooseServiceController.ts, src/main/controllers/service/UnknownServiceController.ts, src/main/locales/cy/choose-service.json, src/main/locales/cy/court-details.json, src/main/locales/cy/service.json, src/main/locales/cy/unknownService.json, src/main/locales/en/unknownService.json, src/main/modules/awilix/index.ts, src/main/routes.ts, src/main/views/unknown-service.njk, src/test/a11y/a11y.ts, src/test/functional/features/unknown-service.feature, src/test/functional/steps/unknown-service.ts, src/test/unit/test/controllers/ChooseServiceAreaController.ts, src/test/unit/test/controllers/UnknownServiceController.ts
https://tools.hmcts.net/jira/browse/FACT-109
Court Name Not Known: Select and view other options
```
[ ] Yes
[√] No
```
=> FACT_109:Court Name Not Known: Select and view other options

src/main/controllers/CourtDetailsController.ts, src/main/utils/CourtDetailsUtils.ts, src/main/views/choose-service.njk, src/main/views/service.njk, src/test/a11y/a11y.ts, src/test/unit/test/controllers/ChooseServiceAreaController.ts, src/test/unit/test/controllers/ChooseServiceController.ts, src/test/unit/test/controllers/CourtDetailsController.ts, src/test/unit/test/utils/CourtDetailsUtils.ts, src/test/unit/test/utils/FactApi.ts
Add some more Pa11y tests for new pages
Increase test coverage
```
[ ] Yes
[x ] No
```
=> Add pa11y tests and test coverage

charts/fact-frontend/values.preview.template.yaml, src/main/views/search/location.njk, src/test/functional/features/court-details.feature
Test https://github.com/hmcts/fact-api/pull/81
=> Add preview API

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Autoscaling Update values.yaml

charts/fact-frontend/Chart.yaml
=> nodejs update for HPA Update Chart.yaml

src/main/controllers/CourtDetailsController.ts, src/main/interfaces/Enquiries.ts, src/main/locales/cy/court-details.json, src/main/locales/cy/template.json, src/main/locales/en/court-details.json, src/main/views/court-details/not-in-person-court.njk, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-139
Add welsh for contact number
```
[ ] Yes
[ ] No
```
=> FACT-182: Add welsh contact numbers

src/main/controllers/service/ChooseServiceAreaController.ts, src/main/interfaces/ServiceAreasData.ts, src/main/views/service-results.njk, src/test/functional/features/view-immigration-result.feature, src/test/unit/test/controllers/ChooseServiceAreaController.ts, src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
https://tools.hmcts.net/jira/browse/FACT-142
Update for service having only one service area
```
[ ] Yes
[ X ] No
```
=> Fact 142 immigration service result

src/main/controllers/service/ServiceSearchResultsController.ts, src/main/interfaces/ServiceAreasData.ts, src/main/interfaces/ServiceSearchResults.ts, src/main/locales/cy/service-results.json, src/main/locales/en/service-results.json, src/main/views/service-results.njk, src/test/unit/test/controllers/ServiceSearchResultsController.ts
Add service areas text to the search results page
```
[ ] Yes
[  X ] No
```
=> Add serviceareas text

src/main/controllers/service/ServiceSearchResultsController.ts, src/main/interfaces/ServiceSearchResults.ts, src/main/locales/cy/service-results.json, src/main/locales/en/service-results.json, src/main/views/service-results.njk, src/test/unit/test/controllers/ServiceSearchResultsController.ts
Merged the two adjacent strings on the search results page as they are both dynamic (rather than the first as first thought).  
```
[ ] Yes
[ X ] No
```
=> Merge two strings into one

package.json, src/main/views/choose-service.njk, src/main/views/service.njk, src/test/a11y/a11y.ts
Fix accessiblity errors identified with Wave plugin
```
[ ] Yes
[x] No
```
=> Fix accessibility error

jest.a11y.config.js, jest.timeout.config.js, src/test/a11y/a11y.ts
Add 30 second timeout for Pa11y tests.
```
[ ] Yes
[x] No
```
=> Fix pa11y timeout

src/main/modules/helmet/index.ts, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/FACT-204
https://tools.hmcts.net/jira/browse/FACT-205
https://tools.hmcts.net/jira/browse/FACT-206
Implement tag manager
=> Add tag manager

src/main/utils/FactApi.ts
=> using new endpoint

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update CPU request, add memory limit, bump chart

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update  limit, bump chart

src/main/controllers/service/ChooseServiceAreaController.ts, src/main/views/template.njk, src/test/functional/features/help-and-navigation.feature, src/test/functional/steps/help-and-navigation.ts
=> Fact 186+199 beta banner and content info

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update CPU request, bump chart

src/main/controllers/service/ServiceAreaRedirect.ts, src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts, src/main/interfaces/PostcodeResultsQuery.ts, src/main/interfaces/PostcodeSearchData.ts, src/main/locales/cy/postcode-results.json, src/main/locales/en/postcode-results.json, src/main/routes.ts, src/main/utils/FactApi.ts, src/main/views/postcode-search.njk, src/test/a11y/a11y.ts, src/test/functional/features/postcode-search.feature, src/test/unit/test/controllers/service/ServiceAreaRedirect.ts, src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts, src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
=> Fact 137 api clean up

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update CPU request250, bump chart

src/main/views/choose-action.njk, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/main/views/postcode-search.njk, src/main/views/search/location.njk, src/main/views/search/option.njk
Remove safe as part of ITHC remediation
=> remove safe

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update CPU request100, bump chart

api/fact-api-stubs.ts, api/service-areas.json, src/main/assets/scss/main.scss, src/main/assets/scss/postcode-results.scss, src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/interfaces/CourtDetailsData.ts, src/main/interfaces/FactRequest.ts, src/main/interfaces/PostcodeResultsData.ts, src/main/interfaces/PostcodeSearchData.ts, src/main/locales/cy/postcode-results.json, src/main/locales/en/postcode-results.json, src/main/utils/FactApi.ts, src/main/views/postcode-results.njk, src/main/views/webpack/css.njk, src/test/a11y/a11y.ts, src/test/functional/features/postcode-results.feature, src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts, src/test/unit/test/utils/FactApi.ts
=> Postcode results clean up

src/main/controllers/service/ChooseServiceController.ts
Fix "I can't find what I'm looking for" radio option
```
[ ] Yes
[x] No
```
=> Fix not find radio option

src/main/locales/cy/template.json, src/main/locales/en/template.json, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/FACT-199
Refactor to use language description
```
[ ] Yes
[ X ] No
```
=> FACT-199: Refactor to use json language files

src/main/locales/cy/court-details.json
=> FACT-182: welsh

src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts, src/main/interfaces/PostcodeResultsData.ts, src/main/locales/cy/postcode-search.json, src/main/locales/en/postcode-search.json
=> Fix service name in template

src/main/views/choose-service.njk, src/main/views/service.njk
Add quotes to html 
```
[ ] Yes
[ X ] No
```
=> Add quotes to html

src/main/locales/cy/postcode-search.json, src/main/locales/en/postcode-search.json, src/main/views/postcode-search.njk
https://tools.hmcts.net/jira/browse/FACT-217
```
[ ] Yes
[X] No
```
=> fact 217 - removing example for postcode

src/main/views/postcode-results.njk
=> displaying distance to 1 decimal place

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml, src/test/functional/features/court-details.feature, src/test/functional/features/postcode-results.feature
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/FACT-224
Change description
Add prod data
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ ] No
=> Fact 224 prod data

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> Update Env, bump chart

config/custom-environment-variables.yaml, src/main/controllers/CourtDetailsController.ts, src/main/locales/en/court-details.json, src/main/views/court-details/in-person-court.njk, src/test/resources/court-details-results.json, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-236
```
[ ] Yes
[X] No
```
=> Fact 236 condition for image

src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts, src/main/locales/cy/postcode-search.json, src/main/locales/en/postcode-search.json, src/main/utils/validation.ts, src/test/functional/features/postcode-search.feature, src/test/functional/steps/postcode-search.ts, src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts, src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts, src/test/unit/test/utils/validation.ts
https://tools.hmcts.net/jira/browse/FACT-202
```
[ ] Yes
[X] No
```
=> Fact 202 postcode error msg

src/test/a11y/a11y.ts
https://tools.hmcts.net/jira/browse/FACT-113
Add pa11y tests
```
[ ] Yes
[ ] No
```
=> Add pa11y tests

src/main/views/choose-action.njk, src/main/views/choose-service.njk, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/main/views/postcode-results.njk, src/main/views/postcode-search.njk, src/main/views/search/location.njk, src/main/views/search/option.njk, src/main/views/service-results.njk, src/main/views/service.njk, src/main/views/template.njk
Remove unused imports.
```
[ ] Yes
[ X ] No
```
=> Removed unused imports

src/main/assets/scss/court-details.scss, src/main/views/webpack/css.njk
=> FACT-241: scale images

src/main/locales/cy/search/option.json, src/main/locales/en/search/option.json
https://tools.hmcts.net/jira/browse/FACT-242
Remove "Field is blank" from error message
```
[ ] Yes
[x] No
```
=> FACT- 242 Remove field is blank from error message

src/main/controllers/service/ServicePostcodeSearchController.ts, src/main/locales/cy/postcode-search.json, src/main/locales/en/postcode-search.json, src/main/views/postcode-search.njk, src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
https://tools.hmcts.net/jira/browse/FACT-238
```
[ ] Yes
[ ] No
```
=> Fact 238 childcare hint

src/main/locales/cy/choose-action.json, src/main/locales/en/choose-action.json
Fix choose action page error message, by removing "Field is blank - "
```
[ ] Yes
[ ] No
```
=> Fix choose action page error message

src/main/locales/cy/court-details.json, src/main/locales/en/court-details.json, src/test/functional/steps/court-details.ts
=> FACT-239: chnage "Additional information" to covid message

src/main/locales/en/unknownService.json
https://tools.hmcts.net/jira/browse/FACT-248
```
[ ] Yes
[] No
```
=> fact 248 - heading change

src/main/locales/cy/template.json, src/main/locales/en/template.json, src/main/utils/FactApi.ts, src/test/functional/features/help-and-navigation.feature, src/test/functional/steps/help-and-navigation.ts
https://tools.hmcts.net/jira/browse/FACT-185
Attach feedback link and fix header to api call.
```
[ ] Yes
[ X ] No
```
=> Fact 185 feedback link

src/main/locales/cy/unknownService.json
=> fix welsh change

src/main/locales/cy/choose-service.json, src/main/locales/cy/court-details.json, src/main/locales/cy/postcode-search.json, src/main/locales/en/choose-service.json
https://tools.hmcts.net/jira/browse/FACT-243
```
[ ] Yes
[x] No
```
=> fact 243 - change error message

src/main/views/court-details/in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-245
```
[ ] Yes
[X] No
```
=> changing tag to div to allow child tags

src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts
https://tools.hmcts.net/jira/browse/FACT-262
Remove hyphens from service area before showing in display text
```
[ ] Yes
[x] No
```
=> Remove hyphens before displaying service area

src/test/functional/steps/court-details.ts
https://tools.hmcts.net/jira/browse/FACT-246
Update cucumber steps for new facility order
```
[ ] Yes
[x] No
```
=> Update cucumber steps for new facility order

src/main/locales/cy/search/location.json, src/main/locales/en/search/location.json, src/main/views/search/location.njk
https://tools.hmcts.net/jira/browse/FACT-279
Change title on search results page
```
[ ] Yes
[ ] No
```
=> FACT-279: DAC - search results

src/main/views/search/location.njk
https://tools.hmcts.net/jira/browse/FACT-280
add role for screen reader
```
[ ] Yes
[ ] No
```
=> FACT-280: DAC - search results role="status"

src/main/locales/cy/choose-action.json, src/main/locales/cy/choose-service.json, src/main/locales/cy/postcode-search.json, src/main/locales/cy/search/location.json, src/main/locales/cy/search/option.json, src/main/locales/cy/service.json, src/main/locales/en/choose-action.json, src/main/locales/en/choose-service.json, src/main/locales/en/postcode-search.json, src/main/locales/en/search/location.json, src/main/locales/en/search/option.json, src/main/locales/en/service.json, src/main/views/choose-action.njk, src/main/views/choose-service.njk, src/main/views/postcode-results.njk, src/main/views/postcode-search.njk, src/main/views/search/location.njk, src/main/views/search/option.njk, src/main/views/service-results.njk, src/main/views/service.njk
https://tools.hmcts.net/jira/browse/FACT-281
Add error to title
```
[ ] Yes
[ ] No
```
=> FACT-281: DAC - Error title

src/main/views/court-details/in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-278
Remove alt text from image
```
[ ] Yes
[ ] No
```
=> FACT-278: DAC - Remove alt text on image

src/test/functional/steps/court-details.ts, src/test/functional/utlis/puppeteer.util.ts
=> fixing test to get text for array of elements

src/main/controllers/CourtDetailsController.ts, src/main/interfaces/Enquiries.ts, src/main/views/court-details/not-in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-251
https://tools.hmcts.net/jira/browse/FACT-253
Amend rule for displayin email address
```
[ ] Yes
[ ] No
```
=> FACT-251, FACT-253: Amend rule for displaying email address

src/main/app.ts, src/main/assets/scss/main.scss, src/main/locales/cy/template.json, src/main/locales/en/template.json, src/main/modules/nunjucks/index.ts, src/main/views/template.njk, src/main/views/webpack/css.njk, src/test/functional/features/cookie-banner.feature, src/test/functional/steps/cookie-banner.ts, src/test/functional/steps/homepage.ts, src/test/functional/support/hooks.ts, src/test/functional/utlis/puppeteer.util.ts
https://tools.hmcts.net/jira/browse/FACT-259
```
[ ] Yes
[ ] No
```
=> Cookie banner

src/main/controllers/search/SearchResultsController.ts, src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/interfaces/PostcodeResultsData.ts, src/main/interfaces/SearchResultsData.ts, src/main/locales/cy/postcode-results.json, src/main/locales/cy/search/location.json, src/main/locales/en/postcode-results.json, src/main/locales/en/search/location.json, src/main/views/postcode-results.njk, src/main/views/search/location.njk, src/test/unit/test/controllers/search/SearchResultsController.ts, src/test/unit/test/controllers/service/ServicePostcodeResultsController.ts
https://tools.hmcts.net/jira/browse/FACT-267
=> FACT-267: singular/plural search results

src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts, src/test/unit/test/controllers/service/ServicePostcodeSearchController.ts
https://tools.hmcts.net/jira/browse/FACT-263
Use service name rather than slug in postcode search pages
=> FACT-263: Use service name rather than slug

src/main/controllers/service/ChooseServiceAreaController.ts, src/test/unit/test/controllers/service/ChooseServiceAreaController.ts
https://tools.hmcts.net/jira/browse/FACT-268
Redirect back to service page, if user cannot find what they are looking for on service area page
=> FACT-268: 

src/main/locales/cy/postcode-results.json, src/main/locales/en/postcode-results.json
https://tools.hmcts.net/jira/browse/FACT-272
Add missing quotes
=> FACT-272: add missing quotes

src/main/views/court-details/not-in-person-court.njk, src/test/functional/features/court-details.feature
https://tools.hmcts.net/jira/browse/FACT-295
Only display related content when external_link
=> FACT-295 Only display related content when external_link

src/main/views/court-details/not-in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-294
Only display fax heading when fax is present
=> FACT-294 Only display fax heading when fax is present

src/main/controllers/CourtDetailsController.ts, src/main/locales/cy/closed-court.json, src/main/locales/en/closed-court.json, src/main/views/court-details/closed-court.njk, src/test/functional/features/closed-court.feature, src/test/functional/steps/closed-court.ts
JIRA link
https://tools.hmcts.net/jira/browse/FACT-265
Change description
Closed court page
=> FACT-265 Closed court page

src/main/views/template.njk
https://tools.hmcts.net/jira/browse/FACT-329
Update analytics scripts
=> FACT-329 update analytics scripts

src/main/views/court-details/not-in-person-court.njk, src/main/views/service-results.njk, src/test/functional/features/postcode-results.feature
https://tools.hmcts.net/jira/browse/FACT-328
only show processing times link for CCMCC and CCBC
=> FACT-328 only show processing times link for CCMCC and CCBC

src/main/controllers/service/ServicePostcodeResultsController.ts
https://tools.hmcts.net/jira/browse/FACT-301
fix postcode search results language change
=> FACT-301 fix postcode search results language change

src/main/views/macros/error-summary.njk, src/test/functional/features/datalayer.feature, src/test/functional/steps/datalayer.ts, src/test/functional/utlis/puppeteer.util.ts
https://tools.hmcts.net/jira/browse/FACT-337
Push error messages to dataLayer
=> FACT-337 add error messages to GA datalayer

src/main/views/template.njk, src/test/functional/features/datalayer.feature, src/test/functional/steps/datalayer.ts
https://tools.hmcts.net/jira/browse/FACT-338
Push page language to dataLayer
=> Fact 338 datalayer language

src/main/controllers/service/ChooseServiceController.ts, src/main/views/choose-action.njk, src/main/views/choose-service.njk, src/main/views/search/option.njk, src/main/views/service.njk, src/main/views/template.njk
https://tools.hmcts.net/jira/browse/FACT-339
Add radio button selection to GA datalayer
=> Fact 339 datalayer user selection

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml, config/custom-environment-variables.yaml, src/main/controllers/CourtDetailsController.ts, src/main/views/court-details/in-person-court.njk, src/main/views/macros/location-seo-metadata.njk, src/test/functional/features/court-seo-metadata.feature, src/test/functional/steps/court-seo-metadata.ts, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-319
Added SEO structured data object for in-person-court details.
```
[ ] Yes
[x] No
```
=> Fact 319 inperson court metadata

src/main/utils/validation.ts
https://tools.hmcts.net/jira/browse/FACT-349
Fix bug in postcode validation where Guildford postcodes are identified as Scottish
=> FACT-349: Fix bug in postcode validation 

src/main/locales/cy/search/location.json, src/main/locales/cy/search/option.json, src/main/locales/en/search/location.json, src/test/functional/features/description-seo-metadata.feature, src/test/functional/steps/description-seo-metadata.ts
https://tools.hmcts.net/jira/browse/FACT-309
Add seo metadata description for search by name page
=> FACT-309 Add seo metadata description for search by name page

src/main/locales/cy/choose-action.json, src/main/locales/en/choose-action.json, src/test/functional/features/childcare-and-parenting-service-area.feature, src/test/functional/features/crime-service-area.feature, src/test/functional/features/description-seo-metadata.feature, src/test/functional/features/family-service-area.feature, src/test/functional/features/harm-and-abuse-service-area.feature, src/test/functional/features/help-and-navigation.feature, src/test/functional/features/money-service-area.feature, src/test/functional/features/no-name.feature, src/test/functional/features/postcode-results.feature, src/test/functional/features/postcode-search.feature, src/test/functional/features/services.feature, src/test/functional/features/view-immigration-result.feature, src/test/functional/features/view-money-claims-result.feature, src/test/functional/steps/description-seo-metadata.ts
https://tools.hmcts.net/jira/browse/FACT-310
Add seo metadata description for choose action page
=> FACT-310 Add seo metadata description for choose action page

src/main/locales/cy/choose-service.json, src/main/locales/en/choose-service.json, src/test/functional/features/childcare-and-parenting-service-area.feature, src/test/functional/features/crime-service-area.feature, src/test/functional/features/description-seo-metadata.feature, src/test/functional/features/family-service-area.feature, src/test/functional/features/harm-and-abuse-service-area.feature, src/test/functional/features/help-and-navigation.feature, src/test/functional/features/money-service-area.feature, src/test/functional/features/services.feature, src/test/functional/features/view-immigration-result.feature, src/test/functional/features/view-money-claims-result.feature, src/test/functional/steps/description-seo-metadata.ts
https://tools.hmcts.net/jira/browse/FACT-311
Add metadata description to choose service page
=> FACT-311 Add metadata description

src/main/locales/cy/postcode-results.json, src/main/locales/cy/service-results.json, src/main/locales/en/postcode-results.json, src/main/locales/en/service-results.json, src/test/functional/features/description-seo-metadata.feature, src/test/functional/features/view-immigration-result.feature, src/test/functional/features/view-money-claims-result.feature, src/test/functional/steps/description-seo-metadata.ts
https://tools.hmcts.net/jira/browse/FACT-318
Add seo metadata description to search results page
=> FACT-318 Add seo metadata description to search results page

src/main/locales/cy/unknownService.json, src/main/locales/en/unknownService.json, src/test/functional/features/description-seo-metadata.feature, src/test/functional/features/unknown-service.feature, src/test/functional/steps/description-seo-metadata.ts
https://tools.hmcts.net/jira/browse/FACT-322
Add seo metadata description to service not found page
=> FACT-322 Add seo metadata description to service not found page

src/main/controllers/CourtDetailsController.ts, src/main/interfaces/Enquiries.ts, src/main/views/court-details/not-in-person-court.njk, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-350
Iterate over 'enquiries' emails and add description in not-in-person court template
=> FACT-350: Iterate over 'enquiries' emails and add description.

src/main/controllers/CourtDetailsController.ts, src/main/locales/cy/closed-court.json, src/main/locales/cy/court-details.json, src/main/locales/en/closed-court.json, src/main/locales/en/court-details.json, src/main/views/court-details/closed-court.njk, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/main/views/template.njk, src/test/functional/features/closed-court.feature, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-320
Based on @nigeldunne 's previous work, re-worked to use court name instead of court slug for page title's and descriptions.
```
[ ] Yes
[X] No
```
=> FACT-320 - Court name in page title and description

src/main/controllers/CourtDetailsController.ts, src/main/interfaces/CourtDetailsData.ts, src/main/utils/CourtDetailsUtils.ts, src/main/utils/validation.ts, src/test/unit/test/utils/CourtDetailsUtils.ts, src/test/unit/test/utils/validation.ts
https://tools.hmcts.net/jira/browse/FACT-357
Introduced new function to handle the injection of service areas into P1 on page. 
Overwrites previous implementation which injected services areas in a non formatted fashion, leading to broken sentences. 
```
[ ] Yes
[X] No
```
=> FACT-357 - Service area listings in not-in-person-court P1

src/main/controllers/CourtDetailsController.ts, src/main/utils/CourtDetailsUtils.ts, src/main/views/court-details/not-in-person-court.njk, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-162
Fixed issue stemming from previous FACT-162 branch that caused issues displaying enquiries data when API results are returned in welsh/cy.
```
[ ] Yes
[X] No
```
=> FACT-162 - Added fix for displaying of Enquiries when lang set to Welsh

src/main/locales/cy/choose-action.json, src/main/locales/cy/choose-service.json, src/main/locales/cy/court-details.json, src/main/locales/cy/service.json, src/main/locales/cy/unknownService.json, src/main/locales/en/choose-action.json, src/main/locales/en/choose-service.json, src/main/locales/en/court-details.json, src/main/locales/en/service.json, src/main/views/choose-action.njk, src/main/views/choose-service.njk, src/main/views/court-details/in-person-court.njk, src/main/views/search/location.njk, src/main/views/service.njk
https://tools.hmcts.net/jira/browse/FACT-361
- Updated and added any missing or incorrect translations in the locale files.
- Updated template files to make use of new translations where not used previously.
```
[ ] Yes
[X] No
```
=> FACT-361 - Implemented changes for go-live requirements

src/test/functional/features/court-details.feature
https://tools.hmcts.net/jira/browse/FACT-367
Updated functional tests to use different courts/data to evaluate instead of previous courts which were only suitable in old prod data.
```
[ ] Yes
[X] No
```
=> FACT-367 - Fix issues with tests using old, unsuitable prod data

src/main/views/template.njk
https://tools.hmcts.net/jira/browse/FACT-333
Added Google site verification metadata tag into page template head block, with the verification code 3glfkE1sBXj7EtEdO0ktOm5kyR9E14kR7yw_yJ6GH4U
```
[ ] Yes
[X] No
```
=> FACT-333 - Added Google site verification metadata tag into page head

README.md, config/default.yaml, src/main/app.ts
https://tools.hmcts.net/jira/browse/FACT-375
Implemented check for mapIt API to see whether service is live or not. Using /quota API endpoint to perform check.
```
[ ] Yes
[X] No
```
=> FACT-375 - Implemented healthcheck for mapit api service

src/test/functional/puppeteer.config.ts
=> remove proxy

src/main/locales/cy/court-details.json, src/main/locales/cy/home.json, src/main/locales/cy/postcode-search.json, src/main/locales/cy/search/location.json, src/main/locales/cy/search/option.json, src/main/locales/cy/service.json
https://tools.hmcts.net/jira/browse/FACT-361
Update the welsh locale files to correct some typo, casing and wording issues.
```
[ ] Yes
[x] No
```
=> FACT-361 - Corrected some welsh language translations

package.json, src/main/assets/scss/main.scss, src/main/index.js, src/main/locales/cy/template.json, src/main/locales/en/template.json, src/main/views/cookies.njk, src/main/views/template.njk, src/main/views/webpack/css.njk, src/main/views/webpack/js.njk, src/test/functional/steps/cookie-banner.ts, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-389
- Created and added new @hmcts/fact-cookie-manager package to replace @dvsa/cookie-manager package.
- Updated cookie banner to make use of GDS styling toolkit cookie banner component with accept-reject style selection.
- Updated footer privacy policy to link to HMCTS privacy policy
- Updated cookie consent page to default to opt-out of optional cookies.
```
[ ] Yes
[X] No
```
=> FACT-389 - Updated cookie manager and cookie consent banner/form

src/main/locales/cy/cookies.json, src/main/locales/cy/template.json, src/main/locales/en/cookies.json, src/main/locales/en/template.json, src/main/views/template.njk
Revised cookie banner notice and rxVisitor cookie duration length notice based on discussions with CO and APM team.
```
[ ] Yes
[X] No
```
=> FACT-374 - Dynatrace Cookie Banner revision

src/main/locales/cy/cookies.json, src/main/locales/en/cookies.json
https://tools.hmcts.net/jira/browse/FACT-374
Updated cookie information for Dynatrace/APM
```
[ ] Yes
[X] No
```
=> FACT-374 - Updated cookie preference page APM description

src/test/smoke/smoke.ts
https://tools.hmcts.net/jira/browse/FACT-424
Update smoke test to check for health endpoint to ensure connecting services are available
```
[ ] Yes
[x] No
```
=> FACT-424 - Update smoke test to check for health endpoint to ensure connecting services are available

src/test/functional/steps/A-Z-court-search.ts
https://tools.hmcts.net/jira/browse/FACT-526
```
[ ] Yes
[ x] No
```
=> FACT-526 changing element order

package.json, yarn.lock
tools.hmcts.net/jira/browse/FACT-588
```
[ ] Yes
[ ] No
```
=> FACT-588 updating the frontend to fix vulnerabilities

src/main/routes.ts
https://tools.hmcts.net/jira/browse/FACT-606
Sanitised query string appended to redirected URL. Unsure if genuine security issue when redirect performed server-side, but put sanitisation in place as precaution.
```
[ ] Yes
[x] No
```
=> FACT-606 - Sanitised query string due to Fortify conerns.

src/main/views/court-details/not-in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-650
```
[ ] Yes
[x] No
```
=> FACT-650 - Moved new content from sidebar to inside email area

src/main/views/court-details/not-in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-673
- Added new temporary section until proper investigation work can be done to get a full solutions for this.
```
[ ] Yes
[x] No
```
=> FACT-673 - Created new temporary section in not-in-person court template

src/main/interfaces/CourtDetailsData.ts, src/main/locales/cy/court-details.json, src/main/locales/en/court-details.json, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/test/functional/steps/court-details.ts
https://tools.hmcts.net/jira/browse/FACT-713
Add "Find out more about" section to in-person and not-in-person court page sidebar
```
[ ] Yes
[x] No
```
=> FACT-713 - Add new 'find out more' sidebar section

src/main/locales/cy/court-details.json, src/main/locales/en/court-details.json, src/main/views/court-details/in-person-court.njk, src/test/functional/features/court-details.feature
Removed breathing space hardcoded from 'this location handles'
```
[ ] Yes
[x] No
```
=> Removed hardcoding of breathing space

charts/fact-frontend/Chart.yaml
- Upgraded nodejs helm-chart version to 2.3.7
```
[ ] Yes
[x] No
```
=> helm-chart-upgrade - Upgraded helm-chart version to 2.3.7

src/main/locales/cy/postcode-search.json, src/main/locales/en/postcode-search.json
https://tools.hmcts.net/jira/browse/FACT-1017
Changed frontend sentence structure on Postcode Search page. 
```
[ ] Yes
[X] No
```
=> Changed frontend sentence structure in English and Welsh

package.json, yarn.lock
=> updating properties volume

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1054
addressing vulnerable dependencies identified by ithc testing
```
[ ] Yes
[X] No
```
=> addressing vulnerable dependencies identified by ithc testing

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml
=> fixing double forward slash image issue

jest.timeout.config.js
=> upping timeout to test accessibility failures

src/main/views/court-details/in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-980
Updating urgent notice to allow hyperlinks
```
[ ] Yes
[x] No
```
=> FACT-980: Allowing urgent notices to use hyperlinks

package.json
=> updating for cves

src/main/controllers/CourtDetailsController.ts, src/main/views/court-details/not-in-person-court.njk
=> adding in areas of law

jest.timeout.config.js
=> upping timeout

package.json, src/main/index.js, src/main/views/webpack/js.njk, src/test/functional/features/court-details.feature, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1166
adding _oauth2_proxy to cookie manifest
```
[ ] Yes
[x ] No
```
=> adding _oauth2_proxy to cookie manifest

package.json, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/test/resources/court-details-results.json, src/test/resources/not-in-person-court-details-results.json
https://tools.hmcts.net/jira/browse/FACT-1169
adding additional court addresses and description field
```
[ ] Yes
[x] No
```
=> adding additional court addresses and description field

package.json, src/main/index.js, src/main/views/cookies.njk, src/main/views/template.njk, src/main/views/webpack/js.njk, src/test/functional/steps/cookie-banner.ts, yarn.lock
- Upgraded cookie manager dependency
- Upgraded relevant views and cookie manager config
```
[ ] Yes
[x] No
```
=> Upgrade to @hmcts/cookie-manager v1.0.0

src/test/a11y/a11y.ts, yarn.lock
[FACT-1071](https://tools.hmcts.net/jira/browse/FACT-1071)
=> Fact 1071 a11y test

src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-1195
remove colons as per FACT-1195
```
[ ] Yes
[x ] No
```
=> remove colons as per FACT-1195

src/main/views/court-details/in-person-court.njk
https://tools.hmcts.net/jira/browse/FACT-1225
links are now allowed so to show them within the front end we need to add the safe keyword.
API changes: https://github.com/hmcts/fact-api/pull/685
```
[ ] Yes
[x] No
```
=> FACT-1225 added safe to allow links to show properly

src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk
=> updating in person/not in person courts

src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk
=> updating labels

src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk
=> updating frontend

src/test/functional/features/A-Z-court-search.feature, src/test/functional/steps/search.ts, src/test/functional/utlis/puppeteer.util.ts
https://tools.hmcts.net/jira/browse/FACT-609
```
[ ] Yes
[x] No
```
=> Modifying functional tests

src/main/controllers/CourtDetailsController.ts, src/main/controllers/service/ChooseServiceAreaController.ts, src/main/controllers/service/ChooseServiceController.ts, src/main/controllers/service/ServiceAreaRedirect.ts, src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/utils/FactApi.ts, src/main/utils/validation.ts, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-1078
removing issues with sonarcube code smells
```
[ ] Yes
[ x ] No
```
=> FACT-1078 fact frontend fix sonarcube code smells

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1160
fixed warnings
```
[ ] Yes
[x ] No
```
=> fixed warnings

renovate.json
https://tools.hmcts.net/jira/browse/FACT-1148
added renovate json file to base of repo
```
[ ] Yes
[ ] No
```
=> added renovate.json file in base directory

src/main/interfaces/CourtDetailsData.ts, src/main/locales/cy/court-details.json, src/main/locales/en/court-details.json, src/main/views/court-details/in-person-court.njk, src/main/views/court-details/not-in-person-court.njk, src/test/unit/test/controllers/CourtDetailsController.ts
https://tools.hmcts.net/jira/browse/FACT-1258
added nunjucks to show tribunal code and family code to front end inc. cy translation.
```
[ ] Yes
[ x ] No
```
=> FACT-1258 changes to show new court codes for tribunal and family

package.json, src/main/views/webpack/css.njk, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1160
update css file name
```
[ ] Yes
[x] No
```
=> update css file name

.github/renovate.json
https://tools.hmcts.net/jira/browse/FACT-1148
removed open-pull-requests-limit line as it was causing configuration error.
```
[ ] Yes
[ x ] No
```
=> renovatebot config error fix

Jenkinsfile_CNP, package.json, src/main/controllers/ProxyController.ts, src/main/routes.ts, src/main/utils/FactApi.ts, src/main/views/webpack/css-template.njk, src/main/views/webpack/css.njk, src/main/views/webpack/js-template.njk, src/main/views/webpack/js.njk, src/test/functional/features/api-proxy.feature, src/test/functional/steps/api-proxy.ts, src/test/resources/court-details-by-court-types-results.json, src/test/unit/test/controllers/ProxyControllerTest.ts, src/test/unit/test/utils/FactApi.ts, webpack.config.js, webpack/htmlWebpack.js, webpack/scss.js, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1253
adding search courts by court types proxy endpoint
```
[ ] Yes
[x] No
```
=> adding search courts by court types proxy endpoint

Jenkinsfile_nightly, charts/fact-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/FACT-1284
```
[ ] Yes
[x] No
```
=> changing to afterSucess on nightly build

charts/fact-frontend/Chart.yaml, src/test/functional/features/view-money-claims-result.feature
=> updating chart

.gitignore, README.md, charts/fact-frontend/Chart.yaml, src/main/controllers/search/SearchOptionController.ts, src/main/locales/en/search/option.json, src/main/views/search/option.njk, src/test/functional/features/help-and-navigation.feature, src/test/functional/steps/search.ts, src/test/unit/test/controllers/search/SearchOptionController.ts
https://tools.hmcts.net/jira/browse/FACT-1294
adding search by postcode to search options
```
[ ] Yes
[x] No
```
=> adding search by postcode to search options

src/main/controllers/ProxyController.ts, src/main/utils/FactApi.ts, src/main/utils/validation.ts, src/test/unit/test/utils/FactApi.ts
https://tools.hmcts.net/jira/browse/FACT-1290
```
[ ] Yes
[x] No
```
=> add error page

package.json, src/main/controllers/AccessibilityStatementController.ts, src/main/controllers/ChooseActionController.ts, src/main/controllers/CookiesController.ts, src/main/controllers/CourtDetailsController.ts, src/main/controllers/HomeController.ts, src/main/controllers/NotFoundPageController.ts, src/main/controllers/search/CourtPrefixSearchController.ts, src/main/controllers/search/LocationSearchController.ts, src/main/controllers/search/SearchOptionController.ts, src/main/controllers/search/SearchResultsController.ts, src/main/controllers/service/ChooseServiceAreaController.ts, src/main/controllers/service/ChooseServiceController.ts, src/main/controllers/service/ServiceAreaRedirect.ts, src/main/controllers/service/ServicePostcodeResultsController.ts, src/main/controllers/service/ServicePostcodeSearchController.ts, src/main/controllers/service/ServiceSearchResultsController.ts, src/main/controllers/service/UnknownServiceController.ts, yarn.lock
https://tools.hmcts.net/jira/browse/FACT-1266
```
[ ] Yes
[x] No
```
=> add doc strings

src/main/modules/helmet/index.ts
https://tools.hmcts.net/jira/browse/FACT-1461
Added dynatrace to allow list.
```
[ ] Yes
[x] No
```
=> FACT-1461 Added dynatrace url to allow list

src/test/config.ts
n/a
adding timeout for func tests using playwright config
```
[ ] Yes
[x] No
```
=> fact frontend fix func tests

Jenkinsfile_CNP, Jenkinsfile_nightly, docker/database/Dockerfile
https://tools.hmcts.net/jira/browse/FACT-1881
trying to change to imported image
```
[ ] Yes
[x] No
```
=> FACT-1881 changed docker db from from to use imported

Jenkinsfile_CNP, Jenkinsfile_nightly
=> FACT-1881 remove bit not needed

src/main/modules/helmet/index.ts
=> FACT-2384 - fix

charts/fact-frontend/Chart.yaml, charts/fact-frontend/values.yaml, src/main/modules/properties-volume/index.ts
This reverts commit 0a5568081444e6b28e8ed9b279f55c7f7d7d78f8.
=> Revert "Update app insights keys (#885)"
